import { useLocation } from 'react-router-dom'
import TimelineView from '../components/copilot/TimelineView'

export default function TimelinePage() {
  const location = useLocation()

  // Use router state if navigated with timeline, else use last saved one
  const events = location.state?.timeline
    || JSON.parse(localStorage.getItem('oo_last_timeline') || '[]')

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 12, color: 'var(--muted)', fontFamily: 'var(--mono)', letterSpacing: '0.08em', marginBottom: 8 }}>
          INCIDENT TIMELINE
        </div>
        <h1 style={{ fontSize: 26, fontWeight: 700 }}>Auto-Built Incident Timeline</h1>
        <p style={{ color: 'var(--muted)', marginTop: 6 }}>
          Showing the most recent timeline generated by the copilot.
        </p>
      </div>

      {events.length === 0 ? (
        <div style={{
          background: 'var(--bg2)', border: '1px solid var(--line)',
          borderRadius: 18, padding: 32, textAlign: 'center', color: 'var(--muted)'
        }}>
          <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 10 }}>No timeline yet</div>
          <div style={{ fontSize: 14 }}>
            Go to the Copilot and ask:<br />
            <span style={{ color: 'var(--cyan)', fontFamily: 'var(--mono)', fontSize: 13 }}>
              "Why did the battery bus voltage drop at 14:32 UTC?"
            </span>
            <br /><br />
            The timeline will appear here automatically after the copilot responds.
          </div>
        </div>
      ) : (
        <div style={{ background: 'var(--bg2)', border: '1px solid var(--line)', borderRadius: 18, padding: 'clamp(16px, 4vw, 28px)' }}>
          <TimelineView events={events} />
        </div>
      )}
    </div>
  )
}